# Generated by Django 4.2.7 on 2026-10-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Название тревоги | Служебная информация')),
                ('header', models.CharField(default='', max_length=128, verbose_name='Заголовок тревоги| Отображается на странице')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Текст тревоги')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
            ],
            options={
                'verbose_name': 'Тревога на страницах',
                'verbose_name_plural': 'Тревоги на страницах',
            },
        ),
        migrations.CreateModel(
            name='WidgetAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Название рекламного блока | Служебная информация')),
                ('header', models.CharField(default='', max_length=128, verbose_name='Заголовок рекламного блока | Отображается на странице')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Текст объявления')),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='Условия объявления')),
                ('image', models.ImageField(default='', upload_to='main_page/adverts', verbose_name='Изображение для рекламного объявления')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар для рекламы через виджет')),
            ],
            options={
                'verbose_name': 'Объявление через виджет',
                'verbose_name_plural': 'Объявления через виджет',
            },
        ),
        migrations.CreateModel(
            name='MainPageInfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(default='', max_length=128, verbose_name='Название рекламного блока | Служебная информация')),
                ('block_header', models.CharField(default='', max_length=128, verbose_name='Заголовок рекламного блока | Отображается на странице')),
                ('block_text', models.TextField(blank=True, default='<li class="hero__list-item t-25">Особенность 1</li>\n                    <li class="hero__list-item t-25">Особенность 2</li>\n                    ', null=True, verbose_name='Описание')),
                ('block_image', models.ImageField(default='', upload_to='main_page/infoblock', verbose_name='Изображение для рекламного блока')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('block_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар для рекламы на главной странице')),
            ],
            options={
                'verbose_name': 'Реклама на главной странице',
                'verbose_name_plural': 'Реклама на главной странице',
            },
        ),
    ]
