# Generated by Django 4.2.7 on 2025-05-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(default='', max_length=128, verbose_name='Название рекламного блока | Служебная информация')),
                ('block_header', models.CharField(default='', max_length=128, verbose_name='Заголовок рекламного блока | Отображается на странице')),
                ('block_brand', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Название бренда | Поле над заголовком | Опционально')),
                ('block_text', models.TextField(blank=True, default='<ul>\n                    <li><span>Особенность 1</span>\xa0</li>\n                    <li><span>Особенность 2</span></li>\n                </ul>', null=True, verbose_name='Описание')),
                ('block_image', models.ImageField(default='', upload_to='main_page/infoblock', verbose_name='Изображение для рекламного блока')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('block_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар для рекламы на главной странице')),
            ],
            options={
                'verbose_name': 'Реклама на главной странице',
                'verbose_name_plural': 'Реклама на главной странице',
            },
        ),
    ]
