# Generated by Django 4.2.7 on 2024-06-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_name', models.CharField(max_length=128, verbose_name='Название рекламного блока')),
                ('advert_text', models.CharField(max_length=256, verbose_name='Текст рекламного блока')),
                ('advert_image', models.ImageField(default='', upload_to='main_page/banner', verbose_name='Изображение для рекламного блока')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('advert_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория для рекламы на главной странице')),
            ],
            options={
                'verbose_name': 'Реклама на главной странице',
                'verbose_name_plural': 'Реклама на главной странице',
            },
        ),
    ]
