# Generated by Django 4.2.7 on 2024-06-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPage',
            new_name='MainPageAdvertisement',
        ),
    ]
