# Generated by Django 4.2.7 on 2024-08-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_offer_shipping_pack_alter_brand_banner_color'),
        ('core', '0002_rename_mainpage_mainpageadvertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=128, verbose_name='Название рекламного блока')),
                ('block_text', models.CharField(max_length=256, verbose_name='Текст рекламного блока')),
                ('block_image', models.ImageField(default='', upload_to='main_page/infoblock', verbose_name='Изображение для рекламного блока')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('block_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория для рекламы на главной странице')),
            ],
            options={
                'verbose_name': 'Реклама на главной странице',
                'verbose_name_plural': 'Реклама на главной странице',
            },
        ),
        migrations.DeleteModel(
            name='MainPageAdvertisement',
        ),
    ]
