# Generated by Django 4.2.7 on 2026-02-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_mainpageinfoblock_block_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageinfoblock',
            name='block_text',
            field=models.TextField(blank=True, default='<ul>\n                    <li class="hero__list-item t-25">Особенность 1</li>\n                    <li class="hero__list-item t-25">Особенность 2</li>\n                </ul>', null=True, verbose_name='Описание'),
        ),
    ]
