# Generated by Django 4.2.7 on 2026-03-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mainpageinfoblock_block_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageinfoblock',
            name='block_text',
            field=models.TextField(blank=True, default='<li class="hero__list-item t-25">Особенность 1</li>\n                    <li class="hero__list-item t-25">Особенность 2</li>\n                    ', null=True, verbose_name='Описание'),
        ),
    ]
