# Generated by Django 4.2.7 on 2026-08-19 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_brand_logo_alter_category_logo_and_more'),
        ('core', '0004_alter_mainpageinfoblock_block_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(default='', max_length=128, verbose_name='Название тревоги | Служебная информация')),
                ('block_header', models.CharField(default='', max_length=128, verbose_name='Заголовок тревоги| Отображается на странице')),
                ('alert_text', models.TextField(blank=True, default='', null=True, verbose_name='Текст тревоги')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
            ],
            options={
                'verbose_name': 'Тревога на страницах',
                'verbose_name_plural': 'Тревоги на страницах',
            },
        ),
        migrations.CreateModel(
            name='WidgetAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_name', models.CharField(default='', max_length=128, verbose_name='Название рекламного блока | Служебная информация')),
                ('advert_header', models.CharField(default='', max_length=128, verbose_name='Заголовок рекламного блока | Отображается на странице')),
                ('advert_text', models.TextField(blank=True, default='', null=True, verbose_name='Текст объявления')),
                ('advert_notes', models.TextField(blank=True, default='', null=True, verbose_name='Условия объявления')),
                ('advert_image', models.ImageField(default='', upload_to='main_page/adverts', verbose_name='Изображение для рекламного объявления')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('advert_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар для рекламы через виджет')),
            ],
            options={
                'verbose_name': 'Объявление через виджет',
                'verbose_name_plural': 'Объявления через виджет',
            },
        ),
    ]
