# Generated by Django 4.2.7 on 2026-08-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_widgetalert_widgetadvertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgetadvertisement',
            old_name='advert_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='widgetadvertisement',
            old_name='advert_header',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='widgetadvertisement',
            old_name='advert_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='widgetadvertisement',
            old_name='advert_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='widgetadvertisement',
            old_name='advert_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='widgetadvertisement',
            old_name='advert_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='widgetalert',
            old_name='block_header',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='widgetalert',
            old_name='alert_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='widgetalert',
            old_name='alert_text',
            new_name='text',
        ),
    ]
