# Generated by Django 4.2.7 on 2026-08-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_advert_category_widgetadvertisement_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgetadvertisement',
            old_name='category',
            new_name='product',
        ),
    ]
