# Generated by Django 4.2.7 on 2024-01-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('catalog', '0001_initial'), ('catalog', '0002_alter_brand_description_alter_category_description_and_more'), ('catalog', '0003_alter_productgroup_categories'), ('catalog', '0004_alter_offer_product_group_and_more'), ('catalog', '0005_alter_offer_name')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название категории')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд, к которому относится категория')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название группы товаров')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд, к которому относится группа товаров')),
                ('categories', models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='Категории, к которым принадлежит группа товаров')),
            ],
            options={
                'verbose_name': 'Группа товара',
                'verbose_name_plural': 'Группы товаров',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, verbose_name='Артикул')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='catalog.productgroup', verbose_name='Группа, к которой принадлежит товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['place'],
            },
        ),
    ]
