# Generated by Django 4.2.7 on 2023-12-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('catalog', '0001_initial'), ('catalog', '0002_alter_brand_options_alter_category_options_and_more'), ('catalog', '0003_remove_category_brand_alter_category_name_and_more'), ('catalog', '0004_alter_category_brand'), ('catalog', '0005_rename_level_category_mptt_level'), ('catalog', '0006_remove_category_lft_remove_category_mptt_level_and_more'), ('catalog', '0007_remove_product_categories_alter_brand_name_and_more'), ('catalog', '0008_remove_category_brand_category_brand'), ('catalog', '0009_offer_alter_product_options_remove_product_category_and_more'), ('catalog', '0010_alter_offer_options_alter_product_options_and_more'), ('catalog', '0011_alter_brand_name_alter_product_categories'), ('catalog', '0012_alter_brand_name_alter_category_brand_and_more'), ('catalog', '0013_alter_offer_options_remove_offer_category_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Бренд')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд, к которому относится категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название группы товаров')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд, к которому относится группа товаров')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('categories', models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='Категории, к которым принадлежит группа товаров')),
            ],
            options={
                'verbose_name': 'Группа товара',
                'verbose_name_plural': 'Группы товаров',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Артикул')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд, к которому относится товар')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='catalog.product', verbose_name='Группа, к которой принадлежит товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['place'],
            },
        ),
    ]
