# Generated by Django 4.2.7 on 2024-04-12 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Бренд')),
                ('logo', models.ImageField(blank=True, default='default.jpg', upload_to='brand/logo', verbose_name='Логотип бренда')),
                ('banner', models.ImageField(blank=True, default='default_banner.jpg', upload_to='brand/banner', verbose_name='Баннер бренда')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='url-адрес')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=256, verbose_name='Название категории')),
                ('logo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='category/logo', verbose_name='Логотип категории')),
                ('banner', models.ImageField(blank=True, default='default_banner.jpg', upload_to='category/banner', verbose_name='Баннер категории')),
                ('instruction', models.FileField(blank=True, null=True, upload_to='files/instructions', verbose_name='Инструкция')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='url-адрес')),
                ('is_final', models.BooleanField(default=False, verbose_name='Отметка о том, что категория является финальной и в ней содержатся товары')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд, к которому относится категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, verbose_name='Артикул')),
                ('tech_info', models.FileField(blank=True, null=True, upload_to='files/instructions', verbose_name='Техзадание')),
                ('ctru', models.CharField(blank=True, max_length=64, null=True, verbose_name='КТРУ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='catalog.category', verbose_name='Категория, к которой принадлежит товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_link', to='catalog.category', verbose_name='Image category')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_link', to='files.modelimage', verbose_name='Category image')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_link', to='catalog.category', verbose_name='file category')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_link', to='files.modelfile', verbose_name='Category file')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='certificate',
            field=models.ManyToManyField(related_name='category_certificate', through='catalog.CategoryFile', to='files.modelfile'),
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(related_name='category', through='catalog.CategoryImage', to='files.modelimage'),
        ),
        migrations.AddField(
            model_name='category',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='catalog.category', verbose_name='Родительские категории'),
        ),
    ]
