# Generated by Django 4.2.7 on 2024-01-27 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='category',
            name='logo',
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(related_name='category', to='files.modelimage'),
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_link', to='catalog.category', verbose_name='Image category')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_link', to='files.modelimage', verbose_name='Category image')),
            ],
        ),
    ]
