# Generated by Django 4.2.7 on 2024-04-20 23:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='instruction',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/home/mega-kenga/PycharmProjects/collabtraining/trainingdjango/privateprivate/'), upload_to='instructions', verbose_name='Инструкция'),
        ),
    ]
