# Generated by Django 4.2.7 on 2023-12-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='ID родительской категории'),
        ),
    ]
