# Generated by Django 4.2.7 on 2024-04-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='instruction',
            field=models.FileField(blank=True, null=True, upload_to='protected/files/instructions', verbose_name='Инструкция'),
        ),
    ]
