# Generated by Django 4.2.7 on 2024-01-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_banner', to='files.bannerimage', verbose_name='Баннер категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд, к которому относится категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_logo', to='files.logoimage', verbose_name='Логотип категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='catalog.category', verbose_name='Родительские категории'),
        ),
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_banner', to='files.bannerimage', verbose_name='Баннер бренда'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_logo', to='files.logoimage', verbose_name='Логотип бренда'),
        ),
    ]
