# Generated by Django 4.2.7 on 2024-02-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_banner', to='files.modelimage', verbose_name='Баннер бренда'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_logo', to='files.modelimage', verbose_name='Логотип бренда'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_banner', to='files.modelimage', verbose_name='Баннер категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='files.modelfile', verbose_name='Регистрационное удостоверение'),
        ),
        migrations.AddField(
            model_name='category',
            name='instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruction', to='files.modelfile', verbose_name='Инструкция'),
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_logo', to='files.modelimage', verbose_name='Логотип категории'),
        ),
        migrations.AddField(
            model_name='offer',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.modelimage', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='offer',
            name='tech_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_description', to='files.modelfile', verbose_name='Техзадание'),
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_link', to='catalog.category', verbose_name='Image category')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_link', to='files.modelimage', verbose_name='Category image')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(related_name='category', through='catalog.CategoryImage', to='files.modelimage'),
        ),
    ]
