# Generated by Django 4.2.7 on 2026-03-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rutube_link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка Rutube'),
        ),
    ]
