# Generated by Django 4.2.7 on 2024-04-21 12:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryimage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='category',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
        migrations.AlterField(
            model_name='category',
            name='instruction',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/home/mega-kenga/Study/pythonProject/trainingdjango/private/'), upload_to='instructions', verbose_name='Инструкция'),
        ),
        migrations.DeleteModel(
            name='CategoryFile',
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
