# Generated by Django 4.2.7 on 2025-03-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True, verbose_name='url-адрес'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True, verbose_name='url-адрес'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True, verbose_name='url-адрес'),
        ),
    ]
