# Generated by Django 4.2.7 on 2024-01-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('catalog', '0002_remove_offer_slug_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='files.catalogimage', verbose_name='Логотип бренда'),
        ),
    ]
