# Generated by Django 4.2.7 on 2024-03-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('catalog', '0002_remove_categoryimage_image_type_remove_offer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='brand/banner', verbose_name='Баннер бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand/logo', verbose_name='Логотип бренда'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='category/banner', verbose_name='Баннер категории'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='certificate',
        ),
        migrations.AlterField(
            model_name='category',
            name='instruction',
            field=models.FileField(blank=True, null=True, upload_to='files/instructions', verbose_name='Инструкция'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='category/logo', verbose_name='Логотип категории'),
        ),
        migrations.CreateModel(
            name='CategoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_link', to='catalog.category', verbose_name='file category')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_link', to='files.modelfile', verbose_name='Category file')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='certificate',
            field=models.ManyToManyField(related_name='category_certificate', through='catalog.CategoryFile', to='files.modelfile'),
        ),
    ]
