# Generated by Django 4.2.7 on 2023-12-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_brand_id_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='catalog.category', verbose_name='ID категории, к которой относится товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(default='', max_length=512, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.category', verbose_name='ID родительской категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.brand', verbose_name='ID бренда, к которому относится товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
