# Generated by Django 4.2.7 on 2024-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_brand_banner_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='banner_color',
            field=models.CharField(default='#3391c5', max_length=32, null=True, verbose_name='Цвет баннера бренда'),
        ),
    ]
