# Generated by Django 4.2.7 on 2024-01-02 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productgroup_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='catalog.productgroup', verbose_name='Группа, к которой принадлежит товар'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='Категории, к которым принадлежит группа товаров'),
        ),
    ]
