# Generated by Django 4.2.7 on 2024-04-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_modelfile_options_alter_modelimage_options_and_more'),
        ('catalog', '0003_remove_categoryimage_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_link', to='catalog.category', verbose_name='Image category')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_link', to='files.modelimage', verbose_name='Category image')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_link', to='catalog.category', verbose_name='file category')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_link', to='files.modelfile', verbose_name='Category file')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='certificate',
            field=models.ManyToManyField(related_name='category_certificate', through='catalog.CategoryFile', to='files.modelfile'),
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(related_name='category', through='catalog.CategoryImage', to='files.modelimage'),
        ),
    ]
