# Generated by Django 4.2.7 on 2024-08-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_brand_banner_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='shipping_pack',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Количество в упаковке'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='banner_color',
            field=models.CharField(default='#3391c5', max_length=32, null=True, verbose_name='Цвет баннера бренда'),
        ),
    ]
