# Generated by Django 4.2.7 on 2024-01-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_catalogimage_options_catalogimage_name'),
        ('catalog', '0003_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.catalogimage', verbose_name='Логотип бренда'),
        ),
    ]
