# Generated by Django 4.2.7 on 2026-04-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='h1_name',
            field=models.TextField(blank=True, default='', null=True, verbose_name='H1 товара'),
        ),
    ]
