# Generated by Django 4.2.7 on 2025-03-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True, verbose_name='url-адрес'),
        ),
    ]
