# Generated by Django 4.2.7 on 2024-03-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_brand_banner_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='brand/logo', verbose_name='Логотип бренда'),
        ),
    ]
