# Generated by Django 4.2.7 on 2024-04-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_categoryimage_categoryfile_category_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryimage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='category',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
        migrations.DeleteModel(
            name='CategoryFile',
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
