# Generated by Django 4.2.7 on 2024-03-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='brand/logo', verbose_name='Логотип бренда'),
        ),
    ]
