# Generated by Django 4.2.7 on 2024-01-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_offer_product_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Артикул'),
        ),
    ]
