# Generated by Django 4.2.7 on 2025-03-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='ceo_description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='title',
        ),
    ]
