# Generated by Django 4.2.7 on 2026-07-17 08:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='brand/logo', verbose_name='Логотип бренда'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='category/logo', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='product/logo', verbose_name='Логотип'),
        ),
    ]
