# Generated by Django 4.2.7 on 2025-03-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_offer_ceo_description_remove_offer_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner_color',
            field=models.CharField(default='#3391c5', max_length=32, null=True, verbose_name='Цвет баннера категории'),
        ),
    ]
