# Generated by Django 4.2.7 on 2024-01-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['place'], 'permissions': [('see_logo', 'Can see logo')], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
    ]
