# Generated by Django 4.2.7 on 2023-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть'),
        ),
        migrations.AddField(
            model_name='category',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть'),
        ),
        migrations.AddField(
            model_name='product',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть'),
        ),
    ]
