# Generated by Django 4.2.7 on 2024-04-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_brand_catalog_bra_place_02297e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='catalog_bra_place_02297e_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_place_bdac70_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_brand_i_cc684c_idx',
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='catalog_off_place_0c9311_idx',
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='catalog_off_categor_a4ac70_idx',
        ),
    ]
