# Generated by Django 4.2.7 on 2024-01-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['place'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
    ]
