# Generated by Django 4.2.7 on 2024-03-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, default='default_banner.jpg', upload_to='brand/banner', verbose_name='Баннер бренда'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, default='default_banner.jpg', upload_to='category/banner', verbose_name='Баннер категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='category/logo', verbose_name='Логотип категории'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tech_info',
            field=models.FileField(blank=True, null=True, upload_to='files/instructions', verbose_name='Техзадание'),
        ),
    ]
