# Generated by Django 4.2.7 on 2024-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_brand_catalog_bra_place_02297e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offer',
            name='catalog_off_place_0c9311_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_final'], name='catalog_cat_is_fina_ad5de8_idx'),
        ),
    ]
