# Generated by Django 4.2.7 on 2024-01-13 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_modelfile'),
        ('catalog', '0008_alter_brand_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.modelfile', verbose_name='Регистрационное удостоверение'),
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.modelimage', verbose_name='Логотип категории'),
        ),
    ]
