# Generated by Django 4.2.7 on 2024-01-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_certificate_category_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
