# Generated by Django 4.2.7 on 2023-12-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_brand_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='place',
            field=models.IntegerField(blank=True, null=True, verbose_name='Место в списке'),
        ),
        migrations.AddField(
            model_name='category',
            name='place',
            field=models.IntegerField(blank=True, null=True, verbose_name='Место в списке'),
        ),
    ]
