# Generated by Django 4.2.7 on 2024-04-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_brand_catalog_bra_place_02297e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='brand/logo', verbose_name='Логотип бренда'),
        ),
    ]
