# Generated by Django 4.2.7 on 2024-01-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_category_unit_delete_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, to='catalog.category', verbose_name='Родительские категории'),
        ),
    ]
