# Generated by Django 4.2.7 on 2024-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='brand/logo', verbose_name='Логотип бренда'),
        ),
    ]
