# Generated by Django 4.2.7 on 2023-12-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_brand_place_category_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='place',
        ),
        migrations.RemoveField(
            model_name='category',
            name='place',
        ),
    ]
