# Generated by Django 4.2.7 on 2024-01-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_category_parent_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.category', verbose_name='Родительские категории'),
        ),
    ]
