# Generated by Django 4.2.7 on 2024-01-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='Место в списке')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Активен'), ('ARCHIVED', 'В архиве')], default='DRAFT', verbose_name='Статус показа на страницах')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Направление')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='url-адрес')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.unit', verbose_name='Родительское направление')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['place'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.unit', verbose_name='Направление, к которому относится категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Родительская категория'),
        ),
    ]
