# Generated by Django 4.2.7 on 2024-01-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_squashed_0013_alter_offer_options_remove_offer_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductGroup',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='product',
            new_name='product_group',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='brand',
        ),
    ]
