# Generated by Django 4.2.7 on 2024-01-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_category_parent_unit_category_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
