# Generated by Django 4.2.7 on 2024-01-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_category_unit_delete_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, to='catalog.category', verbose_name='Родительские категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='parents',
            field=models.ManyToManyField(blank=True, to='catalog.category', verbose_name='Родительские категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_children', to='catalog.category', verbose_name='Родительская категория'),
        ),
    ]
