# Generated by Django 4.2.7 on 2024-01-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_modelfile_file'),
        ('catalog', '0018_remove_category_parent_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_banner', to='files.modelimage', verbose_name='Баннер бренда'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_banner', to='files.modelimage', verbose_name='Баннер категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruction', to='files.modelfile', verbose_name='Инструкция'),
        ),
        migrations.AddField(
            model_name='offer',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.modelimage', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_logo', to='files.modelimage', verbose_name='Логотип бренда'),
        ),
        migrations.AlterField(
            model_name='category',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='files.modelfile', verbose_name='Регистрационное удостоверение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_logo', to='files.modelimage', verbose_name='Логотип категории'),
        ),
    ]
