# Generated by Django 4.2.7 on 2024-01-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_modelfile_file'),
        ('catalog', '0019_brand_banner_category_banner_category_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='ctru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='КТРУ'),
        ),
        migrations.AddField(
            model_name='offer',
            name='tech_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_description', to='files.modelfile', verbose_name='Техзадание'),
        ),
    ]
