# Generated by Django 4.2.7 on 2024-01-09 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
            options={
                'verbose_name': 'Файлы, связанные с главной страницей',
                'verbose_name_plural': 'Файлы, связанные с главной страницей',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnitFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.unit')),
            ],
            options={
                'verbose_name': 'Файлы, связанные с направлениями',
                'verbose_name_plural': 'Файлы, связанные с направлениями',
                'ordering': ['unit'],
            },
        ),
        migrations.CreateModel(
            name='OfferFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('tech_specification', models.FileField(blank=True, null=True, upload_to='tech_specification/')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.offer')),
            ],
            options={
                'verbose_name': 'Файлы, связанные с товарами',
                'verbose_name_plural': 'Файлы, связанные с товарами',
                'ordering': ['offer'],
            },
        ),
        migrations.CreateModel(
            name='CategoryFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='registration_certificate/')),
                ('instruction', models.FileField(blank=True, null=True, upload_to='instruction/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Файлы, связанные с категориями',
                'verbose_name_plural': 'Файлы, связанные с категориями',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='BrandFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo', to='catalog.brand')),
            ],
            options={
                'verbose_name': 'Файлы, связанные с брендами',
                'verbose_name_plural': 'Файлы, связанные с брендами',
                'ordering': ['brand'],
            },
        ),
    ]
