# Generated by Django 4.2.7 on 2024-01-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogimage',
            options={'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
