# Generated by Django 4.2.7 on 2024-03-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modelimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/certificates'),
        ),
    ]
