# Generated by Django 4.2.7 on 2024-04-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_categoryimage_category_and_more'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modelimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='modelfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modelimage',
            name='name',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='modelimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
    ]
