# Generated by Django 4.2.7 on 2024-04-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_modelfile_options_alter_modelimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelfile',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='modelimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='category/certificates'),
        ),
    ]
