# Generated by Django 4.2.7 on 2024-01-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_catalogimage_options_catalogimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
