# Generated by Django 4.2.7 on 2024-03-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_modelfile_name_remove_modelimage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='modelimage',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
