# Generated by Django 4.2.7 on 2024-01-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_brand_options'),
        ('files', '0003_alter_catalogimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogImage',
            new_name='ModelImage',
        ),
    ]
