# Generated by Django 4.2.7 on 2024-04-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_modelfile_options_alter_modelimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelfile',
            options={'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='modelimage',
            options={'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='modelfile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='modelimage',
            name='category',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
