# Generated by Django 4.2.7 on 2024-01-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_rename_catalogimage_modelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('file', models.ImageField(blank=True, null=True, upload_to='files')),
            ],
            options={
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
