# Generated by Django 4.2.7 on 2024-04-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_categoryimage_category_and_more'),
        ('files', '0004_alter_modelfile_options_alter_modelimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelfile',
            options={'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.RemoveField(
            model_name='modelfile',
            name='name',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='modelimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='category/certificates'),
        ),
    ]
