# Generated by Django 4.2.7 on 2024-01-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_modelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
